In [44]:
import numpy as np
import matplotlib.pyplot as plt

import pandas as pd

%matplotlib inline

In [3]:
# The input
datain = np.loadtxt('07a_input.txt',comments=None,dtype=str,usecols=(1,7))

In [4]:
np.unique(datain[:,1])

array(['A', 'B', 'C', 'D', 'E', 'F', 'H', 'I', 'K', 'M', 'O', 'P', 'Q',
       'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z'], dtype='<U1')

In [5]:
# gates not depending on others are: GJLN ! Start with G first because of alphabetical req.


In [6]:
# this is the test data
#datain = np.array([['C','A'],['C','F'],['A','B'],['A','D'],['B','E'],['D','E'],['F','E']])

In [7]:
# define a function that finds the index of a letter
def idx(letter):
    return key.find(letter)

# define a function that determines if a set of instructions has been satisfied
def letterready(letter,time):
    ready = True
    for test in conditions(letter):
        if test[0] not in steparray[time][0]:
            ready = False
    return ready

# define a function that determines which set of instructions applies to a letter
def conditions(letter):
    return datain[np.where(datain[:,1] == letter)[0]]

In [50]:
key = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'

# the timing array will be 5 columns (one for each of five workers)
tarray = np.zeros((2000,5))-1
# also need an equivalent complete steps array
steparray = np.zeros((2000,1)).astype(str)
for i in range(len(steparray)):
    steparray[i] = ''

# for each second, determine if each worker is idle.
# If so, allocate them a piece of work, if possible -- assign their time ahead

#for second in range(tarray.shape[0]):
for second in range(tarray.shape[0]-1):
    for worker in range(tarray.shape[1]):
        if tarray[second,worker] == -1: # if they're idle find work
            
            search = True
            si = -1

            while search == True:
                si += 1
                if letterready(key[si],second) and si not in tarray[:second+1]:
                    search = False
                    steparray[second+61+si] = steparray[second+61+si][0] + key[si]
                    tarray[second:second+61+si,worker] = si
                    #print('starting exec '+key[si]+' at time '+str(second))
                elif si == 25:
                    search = False
    
    steparray[second+1] = ''.join(set(steparray[second][0]+steparray[second+1][0]))
        
    if len(steparray[second][0]) == 26:
        print('Process complete at ' + str(second) + ' seconds!')
        break

# should be more than 955 seconds

Process complete at 967 seconds!


In [42]:
tarray[954]

array([-1., -1., -1., -1., -1.])

In [24]:
letterready('C',750)

False

In [195]:
steparray[700]

array(['TYVMXIQUGFKRZLEJHPDON'], dtype='<U32')

In [104]:
steparray[0]='ABC'

In [109]:
steparray[1]='E'

In [43]:
steparray[60:80]

array([[''],
       [''],
       [''],
       [''],
       [''],
       [''],
       ['G'],
       ['G'],
       ['G'],
       ['JG'],
       ['JG'],
       ['LJG'],
       ['GJL'],
       ['LNJG'],
       ['GNJL'],
       ['LNJG'],
       ['GNJL'],
       ['LNJG'],
       ['GNJL'],
       ['LNJG']], dtype='<U32')

In [49]:
df = pd.DataFrame(tarray[60:80])
df['step'] = steparray[60:80]
df

0    1     2     3    4  step
0    6.0  9.0  11.0  13.0 -1.0      
1    6.0  9.0  11.0  13.0 -1.0      
2    6.0  9.0  11.0  13.0 -1.0      
3    6.0  9.0  11.0  13.0 -1.0      
4    6.0  9.0  11.0  13.0 -1.0      
5    6.0  9.0  11.0  13.0 -1.0      
6   -1.0  9.0  11.0  13.0 -1.0     G
7   -1.0  9.0  11.0  13.0 -1.0     G
8   -1.0  9.0  11.0  13.0 -1.0     G
9   10.0 -1.0  11.0  13.0 -1.0    JG
10  10.0 -1.0  11.0  13.0 -1.0    JG
11  10.0  3.0  -1.0  13.0 -1.0   LJG
12  10.0  3.0  -1.0  13.0 -1.0   GJL
13  10.0  3.0  -1.0  -1.0 -1.0  LNJG
14  10.0  3.0  -1.0  -1.0 -1.0  GNJL
15  10.0  3.0  -1.0  -1.0 -1.0  LNJG
16  10.0  3.0  -1.0  -1.0 -1.0  GNJL
17  10.0  3.0  -1.0  -1.0 -1.0  LNJG
18  10.0  3.0  -1.0  -1.0 -1.0  GNJL
19  10.0  3.0  -1.0  -1.0 -1.0  LNJG

In [191]:
steparray[1999]='ABCDEFGHIJKLMNOPQRSTUVWXYZ'
steparray[0]

array([''], dtype='<U32')

In [25]:
np.zeros((2,5))-1

array([[-1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1.]])

In [200]:
letterready('A',750)

True

In [146]:
steparray[70][0]

'GJ'

In [66]:
True and True and True

True

In [60]:
steparray[0][0]

''

In [57]:
for i in range(len(steparray)):
    steparray[i] = ''

In [61]:
steparray[0] = steparray[0][0] + 'e'

In [62]:
steparray[:10]

array([['e'],
       [''],
       [''],
       [''],
       [''],
       [''],
       [''],
       [''],
       [''],
       ['']], dtype='<U32')

In [42]:
tarray

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       ...,
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [122]:
a = np.array([0,1,2,3,4,5])
a[:3]

array([0, 1, 2])

In [68]:
6 in tarray[0]

True

In [67]:
tarray[0]

array([6., 6., 6., 6., 6.])

In [25]:
fini=''

In [37]:
a = np.zeros((1,3))
a[0,2] = 'string'

ValueError: could not convert string to float: 'string'

In [15]:
datain[0][0] in key

True

In [274]:
for loop in range(25):
#for loop in range(5):
    
    search = True
    si = -1
    
    while search == True:
        si += 1
        if letterready(key[si]) and key[si] not in fini:
            search = False
            executed[si] = 1
            fini += key[si]
            
fini

# not GJLNDFKPTMQXIYHUVREOZSAWCB

'GJKLDFNPTMQXIYHUVREOZSAWCB'