In [1]:
import numpy as np
import matplotlib.pyplot as plt

import pandas as pd

%matplotlib inline

    9 players; last marble is worth 25 points: high score is 32
    10 players; last marble is worth 1618 points: high score is 8317
    13 players; last marble is worth 7999 points: high score is 146373
    17 players; last marble is worth 1104 points: high score is 2764
    21 players; last marble is worth 6111 points: high score is 54718
    30 players; last marble is worth 5807 points: high score is 37305


# my input data: 404 players; last marble is worth 71852 points

In [198]:
# define a function that rings indicies clockwise
def cw(track,idx,deltaidx): # only works for a single trip past the post
    tracklen = len(track)
    if idx + deltaidx < tracklen:
        return idx+deltaidx
    else:
        return (idx + deltaidx) - tracklen

# define a function that rings indicies counterclockwise
def ccw(track,idx,deltaidx): # only works for a single trip past the post
    tracklen = len(track)
    if idx - deltaidx >= 0:
        return idx - deltaidx
    else:
        return idx - deltaidx
    
# define a function that returns the active player
def playnext(player):
    if player == np.nan:
        return 1
    elif player < numberofplayers:
        return player + 1
    else:
        return 1

In [258]:
numberofplayers = 10
lastmarble = 1618

active = 1
marble = 2
player = 2
ring = [0,2,1]
scores = np.zeros((numberofplayers+1,1))

while marble < lastmarble:
    #begin phase
    player = playnext(player)
    marble += 1
    
    if marble%23 != 0: #regular scenario
        ring.insert(cw(ring,active,1)+1,marble)
        active = np.argmax(np.array(ring))
    else:
        scores[player] += marble
        scores[player] += ring[ccw(ring,active,7)]
        active = ccw(ring,active,6)
        del ring[ccw(ring,active,1)]
        active = ccw(ring,active,1)
        

    
#ring,player,active,marble

max(scores)

array([ 9205.])

In [249]:
scores

array([[      0.],
       [ 144363.],
       [ 140395.],
       [ 134478.],
       [ 142089.],
       [ 140994.],
       [ 133158.],
       [ 140034.],
       [ 145362.],
       [ 135443.],
       [ 141359.],
       [ 142718.],
       [ 143049.],
       [ 136208.]])

In [236]:
1618%23

8

In [241]:
del(numberofplayers,numberplayers)

#### 

In [196]:
del ring[ccw(ring,5,2)]
ring

[0, 16, 8, 4, 9, 2, 10, 5, 11, 1, 12, 6, 13, 3, 14, 7, 15]

In [191]:
scores[3]+=20
scores

array([[  0.],
       [  0.],
       [  0.],
       [ 40.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  0.]])

In [104]:
active = 1
marble = 5
player = 3

ring = [0,4,2,1,3]


ring.insert(cw(ring,active,1)+1,marble)

ring


[0, 4, 2, 5, 1, 3]

In [105]:
cw(ring,active,2)

3

In [158]:
test = [0,1,2,12,4,5,6]
test[ccw(test,4,8)]

12

In [160]:
np.argmax(np.array(test))

3

In [69]:
17/4

4.25

In [71]:
17%4

1

In [75]:
45%23

22